// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'aarvy-landing-prod',
    appId: '1:526881833136:web:bb2a27ca397d045c687b75',
    storageBucket: 'aarvy-landing-prod.appspot.com',
    apiKey: 'AIzaSyBT98IOgp73BlqmRLemIN6mowY8vTim5HU',
    authDomain: 'aarvy-landing-prod.firebaseapp.com',
    messagingSenderId: '526881833136',
    measurementId: 'G-1JEP2X8SEW',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};
